// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntityId } from "./EntityId";
import type { StateId } from "./StateId";

/**
 * What the user is currently editing inside a project.
 *
 * Replaces the old `CanvasState::active_sprite` model where the focus
 * was always a sprite. With the library, the focus can be a state
 * inside a `Custom`-kind entity, a Tileset, a Tilemap, or a Reference.
 * `None` is valid — empty libraries and the brief window between
 * "create project" and "create first entity" both produce it.
 */
export type ActiveTarget = { "type": "none" } | { "type": "state", "value": { 
/**
 * Entity that owns the state.
 */
entity_id: EntityId, 
/**
 * State within the entity's `EntityContent::Sprites`.
 */
state_id: StateId, } } | { "type": "tileset", "value": { 
/**
 * The targeted entity.
 */
entity_id: EntityId, } } | { "type": "tilemap", "value": { 
/**
 * The targeted entity.
 */
entity_id: EntityId, } } | { "type": "reference", "value": { 
/**
 * The targeted entity.
 */
entity_id: EntityId, } };
