// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TagId } from "./TagId";

/**
 * Per-entity AI metadata.
 */
export type AiMetadata = { 
/**
 * Auto-tags suggested by VLM analysis but not yet user-confirmed.
 */
suggested_tags?: Array<TagId>, 
/**
 * VLM-generated description used for semantic search. Re-derived
 * when the entity changes.
 */
vlm_summary?: string | null, 
/**
 * Embedding for similarity search. Optional and computed lazily —
 * the entity is fully usable without one.
 */
embedding?: Array<number> | null, };
