// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TagId } from "./TagId";

/**
 * Per-entity AI metadata.
 */
export type AiMetadata = { 
/**
 * Auto-tags suggested by VLM analysis but not yet user-confirmed.
 */
suggested_tags?: Array<TagId>, 
/**
 * VLM-generated description used for semantic search. Re-derived
 * when the entity changes.
 */
vlm_summary?: string | null, 
/**
 * Embedding for similarity search. Optional and computed lazily —
 * the entity is fully usable without one.
 */
embedding?: Array<number> | null, 
/**
 * Per-entity `LoRA` reference. Populated by the B10.5
 * train-entity-lora verb after a successful training run against
 * this entity's canonical reference sheet. **Currently the Replicate
 * weights URL written verbatim by the IPC layer; a future host-side
 * download will replace it with a project-relative path.** When
 * present, anchor payloads built for this entity carry it through to
 * backends, overriding any project-wide `LoRA` for the duration of
 * generations against this entity. `None` means "fall back to the
 * project-wide `LoRA`, if any."
 */
lora_path?: string | null, 
/**
 * Animation-studio working state for this entity — stage, controls,
 * first-frame candidates, approved frame, normalized candidates, the raw
 * video clip, and the video job — as a UI-owned JSON blob. Opaque here on
 * purpose: the studio's shape lives in the frontend, and this lets the
 * user resume the staged pipeline after save/reload. `None` means the
 * studio has never been used for this entity (start fresh).
 */
animation_studio_state?: string | null, };
