// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Facing direction for a directional anchor.
 *
 * East is the horizontal flip of west and is never generated or stored as
 * its own variant — see [`DirectionalAnchors::east_from_west`].
 */
export type AnchorDirection = "south" | "west" | "north" | "east";
