// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnimationId } from "./AnimationId";
import type { FrameRange } from "./FrameRange";
import type { LoopDirection } from "./LoopDirection";
import type { UserData } from "./UserData";

/**
 * A named animation entry referencing a frame range.
 */
export type Animation = { 
/**
 * Stable identifier.
 */
id: AnimationId, 
/**
 * Display name. Exporters use this verbatim as the engine-side
 * clip name; pick something legal for the target runtime.
 */
name: string, 
/**
 * Inclusive range of frames this animation plays.
 */
range: FrameRange, 
/**
 * Direction in which the range plays.
 */
loop_direction: LoopDirection, 
/**
 * Multiplier applied to per-frame durations during playback. `1.0`
 * is the editor speed; `2.0` plays twice as fast.
 */
speed_multiplier: number, 
/**
 * Free-form user metadata.
 */
user_data?: UserData, };
