// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The kind of animation a derived sheet holds.
 */
export type AnimationKind = "idle" | "walk" | "attack";
