// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Loop mode for a tile animation.
 */
export type AnimLoopMode = "loop" | "once" | "ping_pong";
