// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifier of an [`Animation`](super::animation::Animation).
 */
export type AnimationId = number;
