// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Errors surfaced by Tauri commands in `pixhaus-app`.
 *
 * Every command in [`crate::commands`] returns
 * `Result<T, AppCommandError>` so the IPC contract is uniform across
 * the catalog. Variants are tagged on the wire (`kind`) so the UI can
 * switch on them without parsing the diagnostic string.
 */
export type AppCommandError = { "kind": "no_active_project" } | { "kind": "not_found", "message": { 
/**
 * Entity kind: `"sprite"`, `"layer"`, `"frame"`, `"palette"`,
 * `"tileset"`, `"slice"`, `"frame_tag"`, etc.
 */
entity: string, 
/**
 * The ID the caller supplied.
 */
id: bigint, } } | { "kind": "not_found_by_name", "message": { 
/**
 * Entity kind: `"frame_tag"`, `"animation"`, etc.
 */
entity: string, 
/**
 * The name the caller supplied.
 */
name: string, } } | { "kind": "out_of_range", "message": { 
/**
 * What was out of range, in plain text.
 */
detail: string, } } | { "kind": "conflict", "message": { 
/**
 * What conflicted, in plain text.
 */
detail: string, } } | { "kind": "unimplemented", "message": { 
/**
 * The stream that will implement this command (e.g. "S01",
 * "S06"). Lets the UI surface a "coming soon" message keyed
 * to the dependency.
 */
stream: string, } } | { "kind": "validation", "message": { 
/**
 * What was invalid, in plain text.
 */
detail: string, } } | { "kind": "nothing_to_undo" } | { "kind": "nothing_to_redo" } | { "kind": "history_corrupted", "message": { 
/**
 * Human-readable description of the underlying failure (the
 * command label and the wrapped error from
 * `core::undo::Error`).
 */
detail: string, } } | { "kind": "verb_error", "message": { 
/**
 * Human-readable error from the verb runtime.
 */
message: string, } };
