// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntityId } from "./EntityId";
import type { SheetVariantId } from "./SheetVariantId";

export type Approval = {
entity_id: EntityId,
canonical_id: SheetVariantId,
previous_canonical_id: SheetVariantId | null,
palette_size: number,
};
