// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CharacterCard } from "./CharacterCard";
import type { LoraAsset } from "./LoraAsset";
import type { ReferenceAsset } from "./ReferenceAsset";
import type { StyleSwatch } from "./StyleSwatch";

/**
 * Project-scoped reusable assets for reference-sheet workflows.
 */
export type AssetLibrary = { references?: Array<ReferenceAsset>, character_cards?: Array<CharacterCard>, style_swatches?: Array<StyleSwatch>, loras?: Array<LoraAsset>, };
