// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifier of a project-scoped AI asset in
 * [`AssetLibrary`](super::library::AssetLibrary).
 */
export type AssetId = number;
