// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Free-form structured metadata for an asset.
 *
 * Common keys: `name`, `age`, `species`, `era`, `faction`. Open-ended;
 * artists capture whatever matters.
 */
export type AssetInfo = { 
/**
 * Free-form keyed metadata.
 */
fields?: { [key in string]: string }, 
/**
 * Personality / behaviour notes — bullets shown in the sheet panel.
 */
notes?: Array<string>, };
