// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NeighborCondition } from "./NeighborCondition";
import type { TileFlags } from "./TileFlags";
import type { TileIndex } from "./TileIndex";

/**
 * One rule in a custom autotile rule set.
 *
 * Eight neighbor conditions cover all 8 surrounding cells in the order
 * NW, N, NE, W, E, SW, S, SE (matching the `BIT_*` constant order above).
 */
export type AutotileRule = { 
/**
 * Condition for each of the 8 neighbors. Order: NW, N, NE, W, E, SW, S, SE.
 */
conditions: [NeighborCondition, NeighborCondition, NeighborCondition, NeighborCondition, NeighborCondition, NeighborCondition, NeighborCondition, NeighborCondition], 
/**
 * Tile index to emit when all conditions match.
 */
result_tile: TileIndex, 
/**
 * Flags (flip/rotation) to apply to the result tile.
 */
result_flags: TileFlags, };
