// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AutotileRule } from "./AutotileRule";
import type { TileIndex } from "./TileIndex";

/**
 * A user-defined autotile rule set.
 */
export type AutotileRuleSet = { 
/**
 * Rules checked in declaration order; first match wins.
 */
rules: Array<AutotileRule>, 
/**
 * Tile index used when no rule matches.
 */
default_tile: TileIndex, };
