// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-layer blend mode used during composition.
 *
 * `Normal` is the default. Variants are kept as standalone names —
 * payloads are not attached because all compositing parameters live
 * on the layer (`opacity`, `visible`) rather than on the mode.
 */
export type BlendMode = "normal" | "darken" | "multiply" | "color_burn" | "lighten" | "screen" | "color_dodge" | "addition" | "overlay" | "soft_light" | "hard_light" | "difference" | "exclusion" | "subtract" | "divide" | "hue" | "saturation" | "color" | "luminosity";
