// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The shape of the active brush.
 */
export type BrushShape = "circle" | "square" | "pixel";
