// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BrushShape } from "./BrushShape";
import type { PaletteId } from "./PaletteId";

/**
 * The active brush configuration.
 */
export type BrushState = { 
/**
 * Brush shape.
 */
shape: BrushShape, 
/**
 * Brush size in pixels (diameter for circles, side for squares).
 */
size: number, 
/**
 * Index into the active palette for the foreground color.
 */
foreground_index: number, 
/**
 * Index into the active palette for the background color.
 */
background_index: number, 
/**
 * Active palette providing colors for the brush. `None` means
 * fall back to the sprite's first palette.
 */
active_palette?: PaletteId | null, };
