// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FrameIndex } from "./FrameIndex";
import type { LayerId } from "./LayerId";
import type { SpriteId } from "./SpriteId";

/**
 * Active viewport configuration.
 */
export type CanvasState = { 
/**
 * Sprite currently being edited. `None` means the project is
 * open but no sprite is foregrounded yet.
 */
active_sprite?: SpriteId | null, 
/**
 * Layer currently selected for editing.
 */
active_layer?: LayerId | null, 
/**
 * Frame currently shown in the viewport.
 */
active_frame?: FrameIndex | null, 
/**
 * Viewport scroll offset in canvas pixels (float so the viewport
 * can interpolate between integer canvas positions during pans).
 */
scroll_x: number, 
/**
 * Viewport scroll offset in canvas pixels (vertical).
 */
scroll_y: number, 
/**
 * Zoom factor. `1.0` is one canvas pixel per screen pixel.
 */
zoom: number, 
/**
 * Whether the editor is in onion-skin mode.
 */
onion_skin: boolean, 
/**
 * Whether tile grid lines render over tilemap layers.
 */
show_tile_grid: boolean, };
