// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CelData } from "./CelData";
import type { FrameIndex } from "./FrameIndex";
import type { IVec2 } from "./IVec2";
import type { LayerId } from "./LayerId";
import type { UserData } from "./UserData";

/**
 * One cel in a sprite's `(layer, frame)` grid.
 *
 * Cels are stored in a flat `Vec<Cel>` on the sprite. A cel is
 * addressed by the `(layer_id, frame_index)` pair; missing cells
 * (a layer with no content on a particular frame) simply have no
 * entry in the vector.
 */
export type Cel = { 
/**
 * Layer this cel belongs to.
 */
layer_id: LayerId, 
/**
 * Timeline position of the cel.
 */
frame_index: FrameIndex, 
/**
 * Top-left placement of the cel content within the canvas.
 * Cels may sit partially or fully off-canvas.
 */
position: IVec2, 
/**
 * Per-cel opacity, multiplied with the layer's opacity at
 * composition time.
 */
opacity: number, 
/**
 * Variant payload (raster pixel handle, tilemap grid, or link).
 */
data: CelData, 
/**
 * Free-form user metadata.
 */
user_data?: UserData, };
