// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FrameIndex } from "./FrameIndex";
import type { PixelBufferId } from "./PixelBufferId";
import type { Size } from "./Size";
import type { TilemapData } from "./TilemapData";

/**
 * Variant payload for a [`Cel`].
 *
 * `Raster` and `Tilemap` carry their own data; `Linked` borrows from
 * another frame on the same layer to keep file size down for cels
 * that don't change between frames.
 */
export type CelData = { "kind": "raster", 
/**
 * Handle into the pixel-buffer registry.
 */
buffer: PixelBufferId, 
/**
 * Width and height of the cel content. Stride is owned by
 * the buffer subsystem and is not part of the data model.
 */
size: Size, } | { "kind": "tilemap", 
/**
 * The tile grid for this `(layer, frame)` cell.
 */
data: TilemapData, } | { "kind": "linked", 
/**
 * Frame whose cel on the same layer holds the source data.
 */
source_frame: FrameIndex, };
