// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DerivedSheet } from "./DerivedSheet";
import type { DirectionalAnchors } from "./DirectionalAnchors";
import type { SheetVariant } from "./SheetVariant";

/**
 * The character anchor cascade for a sprite entity.
 *
 * The hero `canonical` lives on the parent [`ReferenceSheet`]. This struct
 * adds the downstream layers the animation pipeline derives from it:
 *
 * - `neutral` — the canonical stripped of baked-in effects (no glow,
 *   fireball, charged weapon, spell trail). Animations root here, not on the
 *   hero shot, so per-attack effects can be added cleanly later.
 * - `directional` — south / west / north anchors derived from `neutral`
 *   (east is the flip of west).
 * - `derived_sheets` — the idle / walk / attack sheets derived from the
 *   directional anchors.
 *
 * Each layer points at its source via `parent_variant_id` / `derived_from`,
 * so re-rolling the canonical pose cascades staleness down the chain.
 */
export type CharacterAnchor = { 
/**
 * The effect-stripped neutral anchor. `parent_variant_id == canonical.id`.
 */
neutral?: SheetVariant | null, 
/**
 * Directional anchors derived from the neutral variant.
 */
directional?: DirectionalAnchors, 
/**
 * Animation sheets derived from the directional anchors.
 */
derived_sheets?: Array<DerivedSheet>, };
