// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetId } from "./AssetId";

/**
 * Bundle of references and style notes representing one character.
 */
export type CharacterCard = { id: AssetId, name: string, references?: Array<AssetId>, style_notes?: string, associated_lora?: AssetId | null, created_at: number, };
