// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatTurn } from "./ChatTurn";

/**
 * Full chat transcript stored for conversational variant provenance.
 */
export type ChatTranscript = { summary?: string | null, turns?: Array<ChatTurn>, };
