// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReferenceImage } from "./ReferenceImage";
import type { SheetVariantId } from "./SheetVariantId";

/**
 * One conversational editing turn and the variant it produced.
 */
export type ChatTurn = { timestamp: number, user_message: string, mask?: ReferenceImage | null, resulting_variant_id: SheetVariantId, };
