// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Rgba } from "./Rgba";

/**
 * A flat background colour to key out to transparency.
 *
 * Generated sheets use a solid magenta (`#FF00FF`) or green (`#00FF00`)
 * backdrop so the subject silhouette is unambiguous; chroma-keying turns
 * that backdrop into alpha without touching the subject.
 */
export type ChromaKey = { 
/**
 * The background colour to remove (alpha is ignored on the key).
 */
color: Rgba, 
/**
 * Per-channel tolerance. A pixel keys out when every channel is
 * within `tolerance` of `color`. `0` keys only exact matches.
 */
tolerance: number, };
