// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Collision shape for a tile.
 *
 * Full-tile collision is the common case for opaque wall tiles.
 * Explicit `None` marks a tile as passable (decorations, overlays).
 * Additional shapes (slope, partial) are deferred to future streams.
 */
export type CollisionShape = "none" | "full";
