// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The color authoring mode of a sprite.
 *
 * Pixhaus stores all rendered pixels as RGBA internally, but the
 * editor restricts what an artist can place based on mode.
 * Indexed-mode sprites carry palette indices and resolve to RGBA at
 * the render boundary; this is reflected in the per-cel data layout
 * (a separate stream owns that pixel buffer code).
 */
export type ColorMode = "rgba" | "grayscale" | "indexed";
