// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PromptTemplate } from "./PromptTemplate";
import type { Structure } from "./Structure";
import type { Style } from "./Style";

/**
 * The full composition library: project-tier records plus the read-only
 * built-in registry. Project records shadow built-ins by id.
 */
export type CompositionLibrary = { 
/**
 * Project-tier Structures.
 */
structures: Array<Structure>, 
/**
 * Project-tier Styles.
 */
styles: Array<Style>, 
/**
 * Project-tier saved Prompts.
 */
prompts: Array<PromptTemplate>, 
/**
 * Built-in Structures, in id order.
 */
builtin_structures: Array<Structure>, 
/**
 * Built-in Styles, in id order.
 */
builtin_styles: Array<Style>, 
/**
 * Built-in saved Prompts, in id order.
 */
builtin_prompts: Array<PromptTemplate>, };
