// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a `.pixstyle` import resolves an id that already exists in the target.
 */
export type ConflictPolicy = "skip" | "overwrite" | "import_as_copy";
