// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnchorDirection } from "./AnchorDirection";
import type { AnimationKind } from "./AnimationKind";
import type { SheetVariantId } from "./SheetVariantId";

/**
 * One animation sheet derived from a directional anchor, with the edge back
 * to its source for staleness tracking.
 */
export type DerivedSheet = { 
/**
 * Which animation this sheet holds.
 */
animation_kind: AnimationKind, 
/**
 * Which direction it was generated for.
 */
direction: AnchorDirection, 
/**
 * The `FrameTag` / `Animation` name this sheet landed as on the sprite.
 */
tag_name: string, 
/**
 * The directional anchor variant id this was animated from. When the
 * upstream directional anchor changes id, this sheet is stale.
 */
derived_from: SheetVariantId, };
