// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SheetVariant } from "./SheetVariant";

/**
 * Directional anchors derived from the neutral variant.
 *
 * Each directional variant carries `parent_variant_id == neutral.id` so the
 * staleness cascade can walk the edge back. East is the horizontal flip of
 * west, so it conditions on the west variant and is not stored separately.
 */
export type DirectionalAnchors = { 
/**
 * South (front) directional anchor.
 */
south?: SheetVariant | null, 
/**
 * West (side) directional anchor. East flips this.
 */
west?: SheetVariant | null, 
/**
 * North (back) directional anchor.
 */
north?: SheetVariant | null, 
/**
 * `true` once east is enabled — east derives from west by a horizontal
 * flip rather than its own generation.
 */
east_from_west: boolean, };
