// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifier of an [`Entity`](super::library::Entity) in the project library.
 *
 * Stable across renames so cross-entity references (group membership,
 * tilemap-to-tileset) and per-entity AI metadata survive when the user
 * renames an entity.
 */
export type EntityId = number;
