// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiMetadata } from "./AiMetadata";
import type { EntityContent } from "./EntityContent";
import type { EntityDefaults } from "./EntityDefaults";
import type { EntityId } from "./EntityId";
import type { EntityKind } from "./EntityKind";
import type { GroupId } from "./GroupId";
import type { TagId } from "./TagId";
import type { UserData } from "./UserData";

/**
 * A named entity in the project library.
 *
 * The unit of organization for everything in a project: a Hero, an
 * Enemy, a Forest tileset, a Forest-1 level. Stable ids let renames
 * happen without breaking cross-entity references (tilemap-to-tileset,
 * group membership) or per-entity AI metadata.
 */
export type Entity = { 
/**
 * Stable id. Cross-entity references use this; renames don't break.
 */
id: EntityId, 
/**
 * Entity kind determines the content shape. See [`EntityKind`].
 */
kind: EntityKind, 
/**
 * Display name. User-editable.
 */
name: string, 
/**
 * Optional group membership.
 */
group_id?: GroupId | null, 
/**
 * Tag ids attached to this entity.
 */
tags?: Array<TagId>, 
/**
 * Defaults inherited by states/content within this entity.
 */
defaults?: EntityDefaults, 
/**
 * The actual content. Shape depends on `kind`.
 */
content: EntityContent, 
/**
 * Per-entity AI metadata: which sprites within this entity are
 * part of the style reference corpus, prompt history.
 */
ai?: AiMetadata, 
/**
 * Free-form user data (text + tint), reusing existing
 * [`UserData`].
 */
user_data?: UserData, 
/**
 * UTC seconds-since-epoch at which the entity was created. `i64` on
 * the Rust side keeps the full range; TS mirror is `number` since
 * any realistic timestamp fits in `Number.MAX_SAFE_INTEGER`.
 */
created_at: number, 
/**
 * UTC seconds-since-epoch of the last edit to this entity.
 */
updated_at: number, };
