// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NamedSprite } from "./NamedSprite";
import type { ReferenceSheet } from "./ReferenceSheet";
import type { TilemapScene } from "./TilemapScene";
import type { Tileset } from "./Tileset";

/**
 * Type-specific content. Variants line up with [`EntityKind`].
 *
 * The `tag = "type", content = "value"` form mirrors [`EntityKind`]'s
 * shape and disambiguates the wrapper from the field name on the TS
 * side.
 *
 * `clippy::large_enum_variant` fires here because [`Sprite`] (the
 * `Sprites` variant inlines a `Vec<NamedSprite>` of full sprites) is
 * substantially larger than the unit variants. The B9.1-cleanup
 * regression test (`entity_content_size_is_bounded`) measured
 * `size_of::<ReferenceSheet>() > size_of::<Sprite>()`, so the
 * `Reference` variant is boxed: `Reference { sheet: Box<ReferenceSheet> }`.
 * `Sprites` stays inline because boxing it would force an allocation
 * on every library walk in the hot read path. The regression test
 * pins both invariants — flip the boxing decision if `Sprite` ever
 * outgrows [`ReferenceSheet`], and update both the rustdoc here and
 * the test in lockstep. The TS mirror unwraps `Box` automatically so
 * the generated type stays
 * `{ type: "Reference"; value: { sheet: ReferenceSheet } }`.
 */
export type EntityContent = { "type": "Sprites", "value": { 
/**
 * Ordered states. The first entry is the primary/default state
 * for thumbnails and the editor open-on-create flow.
 */
states: Array<NamedSprite>, } } | { "type": "Tileset", "value": { 
/**
 * The tileset payload.
 */
tileset: Tileset, } } | { "type": "Tilemap", "value": { 
/**
 * The scene payload.
 */
scene: TilemapScene, } } | { "type": "Reference", "value": { 
/**
 * The structured reference sheet payload.
 */
sheet: ReferenceSheet, } };
