// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColorMode } from "./ColorMode";
import type { PaletteId } from "./PaletteId";
import type { Pivot } from "./Pivot";
import type { Size } from "./Size";

/**
 * Defaults inherited by states/content under the entity.
 *
 * Every field is optional so an entity that hasn't expressed any
 * defaults serialises as `{}` and round-trips identically.
 */
export type EntityDefaults = { 
/**
 * Default canvas size for new states.
 */
canvas_size?: Size | null, 
/**
 * Default color mode for new states.
 */
color_mode?: ColorMode | null, 
/**
 * Default palette id (refers to a palette in [`Library::palettes`]).
 */
default_palette_id?: PaletteId | null, 
/**
 * Default pivot for sprite handoff.
 */
default_pivot?: Pivot | null, 
/**
 * Default playback FPS for new animation states.
 */
default_fps?: number | null, };
