// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NamedSprite } from "./NamedSprite";
import type { ReferenceSheet } from "./ReferenceSheet";
import type { TilemapScene } from "./TilemapScene";
import type { Tileset } from "./Tileset";

/**
 * Type-specific content. Variants line up with [`EntityKind`].
 *
 * The `tag = "type", content = "value"` form mirrors [`EntityKind`]'s
 * shape and disambiguates the wrapper from the field name on the TS
 * side.
 *
 * `clippy::large_enum_variant` fires here because [`Sprite`] and
 * [`ReferenceSheet`] are both substantially larger than the unit
 * payloads, but boxing would force an extra allocation on every
 * content access in the hot library-walk paths and changes the TS
 * shape; the size disparity is part of the data model.
 */
export type EntityContent = { "type": "Sprites", "value": { 
/**
 * Ordered states. The first entry is the primary/default state
 * for thumbnails and the editor open-on-create flow.
 */
states: Array<NamedSprite>, } } | { "type": "Tileset", "value": { 
/**
 * The tileset payload.
 */
tileset: Tileset, } } | { "type": "Tilemap", "value": { 
/**
 * The scene payload.
 */
scene: TilemapScene, } } | { "type": "Reference", "value": { 
/**
 * The structured reference sheet payload.
 */
sheet: ReferenceSheet, } };
