// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NamedSprite } from "./NamedSprite";
import type { ReferenceSheet } from "./ReferenceSheet";
import type { TilemapScene } from "./TilemapScene";
import type { Tileset } from "./Tileset";

export type EntityContent = { "type": "Sprites", "value": {
states: Array<NamedSprite>,
reference_sheet?: ReferenceSheet | null,
} } | { "type": "Tileset", "value": {
tileset: Tileset,
} } | { "type": "Tilemap", "value": {
scene: TilemapScene,
} };
