// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Kinds of entity. Two system kinds plus one user-defined kind.
 *
 * The data model deliberately does not bake game-genre taxonomy.
 * "Character", "Enemy", "Hero", "Boss" — none of those are kinds. They
 * live in the [`EntityKind::Custom`] variant where the string is the
 * user's category name.
 *
 * The `tag = "kind", content = "value"` form keeps the unit variants
 * small (`{ "kind": "Tileset" }`) while letting `Custom` carry its
 * string in a uniform shape (`{ "kind": "Custom", "value": "Hero" }`).
 */
export type EntityKind = { "kind": "Tileset" } | { "kind": "Tilemap" } | { "kind": "Custom", "value": string };
