// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GroupId } from "./GroupId";
import type { UserData } from "./UserData";

/**
 * A folder-style group within the library tree. Optional, never
 * auto-created.
 */
export type EntityGroup = { 
/**
 * Stable identifier.
 */
id: GroupId, 
/**
 * Display name in the library tree.
 */
name: string, 
/**
 * Optional parent for nested groups. `None` means top-level.
 */
parent_id?: GroupId | null, 
/**
 * Free-form user data (text + tint).
 */
user_data?: UserData, };
