// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Optional features advertised by the writer.
 *
 * Every flag is a single bit. Adding a flag is additive (bump
 * [`SchemaVersion::MINOR`]); removing or repurposing one is a break
 * (bump `MAJOR`). The serialized form is a `u32` so flags persist as
 * a compact bitfield rather than a JSON array.
 */
export type FeatureFlags = number;
