// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FrameRange } from "./FrameRange";
import type { LoopDirection } from "./LoopDirection";
import type { UserData } from "./UserData";

/**
 * A named, contiguous range of frames in the timeline.
 *
 * Used for editor organization and as the source of truth for
 * per-tag playback options. Engine-side animation entries (see
 * [`super::animation::Animation`]) may mirror these or extend them
 * with handoff-specific metadata.
 */
export type FrameTag = { 
/**
 * Display name in the timeline.
 */
name: string, 
/**
 * Inclusive range of frames covered by the tag.
 */
range: FrameRange, 
/**
 * Direction in which the range plays.
 */
loop_direction: LoopDirection, 
/**
 * Number of times the tag should repeat. `0` is conventionally
 * "loop forever"; a positive value bounds playback.
 */
repeat: number, 
/**
 * Free-form user metadata.
 */
user_data?: UserData, };
