// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Position of a frame in the timeline. Frames are dense and
 * 0-indexed, but the type is a newtype so it cannot be confused
 * with a layer ID at a call site.
 */
export type FrameIndex = number;
