// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FrameIndex } from "./FrameIndex";

/**
 * Inclusive range of frames `[start, end]`.
 *
 * `end < start` is rejected at the editor layer; the type itself
 * permits any pair so deserialization of malformed files surfaces a
 * validation error rather than failing to parse.
 */
export type FrameRange = { 
/**
 * First frame in the range, inclusive.
 */
start: FrameIndex, 
/**
 * Last frame in the range, inclusive.
 */
end: FrameIndex, };
