// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserData } from "./UserData";

/**
 * A single frame in the timeline.
 *
 * `duration_ms` is independent of any frame tag's playback speed —
 * tags multiply, they don't replace.
 */
export type Frame = { 
/**
 * Display duration in milliseconds. The minimum honoured by
 * downstream players (Unity importer, web preview) is `1`.
 */
duration_ms: number, 
/**
 * Free-form user metadata.
 */
user_data?: UserData, };
