// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-frame alpha bounding box and the derived placement landmarks.
 *
 * All coordinates are in the frame's own pixel space. A fully transparent
 * frame has no bbox; its landmarks default to the frame centre / bottom so
 * downstream maths never divides by zero.
 */
export type FrameMetrics = { 
/**
 * Left edge of the opaque bounding box.
 */
bbox_x: number, 
/**
 * Top edge of the opaque bounding box.
 */
bbox_y: number, 
/**
 * Width of the opaque content (`0` for a fully transparent frame).
 */
visible_width: number, 
/**
 * Height of the opaque content (`0` for a fully transparent frame).
 */
visible_height: number, 
/**
 * Horizontal centre of the opaque content.
 */
center_x: number, 
/**
 * Bottom row of opaque pixels — the foot baseline. For a transparent
 * frame this is the frame's bottom edge.
 */
foot_baseline_y: number, 
/**
 * `true` when the frame had no opaque pixels.
 */
empty: boolean, };
