// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Provenance for a generated sheet variant.
 */
export type GenerationProvenance = { 
/**
 * Backend that produced the sheet (e.g. `anthropic`, `stability`,
 * `replicate`).
 */
backend: string, 
/**
 * Model identifier used for the run.
 */
model: string, 
/**
 * The prompt that produced this variant.
 */
prompt: string, 
/**
 * Seed for reproducible regeneration. `None` if the backend does
 * not expose seeds.
 */
seed?: bigint | null, 
/**
 * Negative prompt, if used.
 */
negative_prompt?: string | null, };
