// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifier of an [`EntityGroup`](super::library::EntityGroup).
 *
 * Groups are folder-style containers in the library tree; stable ids let
 * a renamed group keep its membership intact.
 */
export type GroupId = number;
