// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which rows or columns take the half-step offset in a hex grid.
 *
 * Only meaningful when [`TileShape`] is `HexPointy` (rows) or `HexFlat`
 * (columns). Adopted from Pixelorama's `tile_offset_axis`.
 */
export type HexOffsetAxis = "odd_row" | "even_row" | "odd_col" | "even_col";
