// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Counts of records affected by a merge.
 */
export type ImportReport = { 
/**
 * Records added (new id, or `.copy` under `ImportAsCopy`).
 */
imported: number, 
/**
 * Records skipped because their id already existed under `Skip`.
 */
skipped: number, 
/**
 * Records replaced because their id already existed under `Overwrite`.
 */
overwritten: number, };
