// Barrel re-export for the data-model bindings generated by ts-rs.
//
// The individual files under this directory are auto-written by
// `cargo test -p pixhaus-core`. Keep imports in UI code pointed at
// this barrel so a future move of the generator (e.g. a different
// output dir) only changes one file.

export type { AnimLoopMode } from "./AnimLoopMode";
export type { Animation } from "./Animation";
export type { AnimationId } from "./AnimationId";
export type { AppCommandError } from "./AppCommandError";
export type { AutotileKind } from "./AutotileKind";
export type { AutotileRule } from "./AutotileRule";
export type { AutotileRuleSet } from "./AutotileRuleSet";
export type { BlendMode } from "./BlendMode";
export type { BrushShape } from "./BrushShape";
export type { BrushState } from "./BrushState";
export type { CanvasState } from "./CanvasState";
export type { Cel } from "./Cel";
export type { CelData } from "./CelData";
export type { CollisionShape } from "./CollisionShape";
export type { ColorMode } from "./ColorMode";
export type { FeatureFlags } from "./FeatureFlags";
export type { Frame } from "./Frame";
export type { FrameIndex } from "./FrameIndex";
export type { FrameRange } from "./FrameRange";
export type { FrameTag } from "./FrameTag";
export type { IVec2 } from "./IVec2";
export type { Layer } from "./Layer";
export type { LayerId } from "./LayerId";
export type { LayerKind } from "./LayerKind";
export type { LoopDirection } from "./LoopDirection";
export type { NeighborCondition } from "./NeighborCondition";
export type { NineSlice } from "./NineSlice";
export type { Palette } from "./Palette";
export type { PaletteEntry } from "./PaletteEntry";
export type { PaletteFrameOverride } from "./PaletteFrameOverride";
export type { PaletteId } from "./PaletteId";
export type { Pivot } from "./Pivot";
export type { PixelBufferId } from "./PixelBufferId";
export type { Project } from "./Project";
export type { ProjectMetadata } from "./ProjectMetadata";
export type { Rect } from "./Rect";
export type { Rgba } from "./Rgba";
export type { SchemaVersion } from "./SchemaVersion";
export type { SelectionRegion } from "./SelectionRegion";
export type { SelectionState } from "./SelectionState";
export type { Size } from "./Size";
export type { Slice } from "./Slice";
export type { SliceId } from "./SliceId";
export type { SliceKey } from "./SliceKey";
export type { Sprite } from "./Sprite";
export type { SpriteId } from "./SpriteId";
export type { TileAnimation } from "./TileAnimation";
export type { TileAnimationFrame } from "./TileAnimationFrame";
export type { TileCell } from "./TileCell";
export type { TileFlags } from "./TileFlags";
export type { TileIndex } from "./TileIndex";
export type { TileProperties } from "./TileProperties";
export type { TilemapData } from "./TilemapData";
export type { Tileset } from "./Tileset";
export type { TilesetId } from "./TilesetId";
export type { TilesetSource } from "./TilesetSource";
export type { UserData } from "./UserData";
