// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A 2D integer point. Negative coordinates are valid (cels can sit
 * off-canvas, references can be placed before the origin).
 */
export type IVec2 = { 
/**
 * Horizontal coordinate.
 */
x: number, 
/**
 * Vertical coordinate.
 */
y: number, };
