// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlendMode } from "./BlendMode";
import type { LayerEffect } from "./LayerEffect";
import type { LayerId } from "./LayerId";
import type { LayerKind } from "./LayerKind";
import type { UserData } from "./UserData";

/**
 * A single layer in a sprite.
 */
export type Layer = { 
/**
 * Stable identifier for this layer.
 */
id: LayerId, 
/**
 * Display name shown in the layer panel.
 */
name: string, 
/**
 * Variant-specific payload (raster, group, tilemap, reference).
 */
kind: LayerKind, 
/**
 * Composition blend mode.
 */
blend_mode: BlendMode, 
/**
 * Opacity, `0` (invisible) through `255` (fully opaque).
 */
opacity: number, 
/**
 * Whether the layer renders. Hidden layers are still part of the
 * document; they just don't contribute to the composite.
 */
visible: boolean, 
/**
 * Whether the layer is locked against edits.
 */
locked: boolean, 
/**
 * Parent group, if any. `None` means a top-level layer.
 */
parent?: LayerId | null, 
/**
 * Non-destructive effects applied to this layer's composited pixels
 * in order at render time. Empty by default; files written before
 * effects existed load with an empty stack and re-save with the field
 * omitted from the wire form.
 */
effects?: Array<LayerEffect>, 
/**
 * Free-form user metadata.
 */
user_data?: UserData, };
