// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IVec2 } from "./IVec2";
import type { PixelBufferId } from "./PixelBufferId";
import type { TilesetId } from "./TilesetId";

/**
 * Variant payload for a [`Layer`].
 *
 * The payload distinguishes the four supported layer kinds. Group
 * layers carry only display state because their pixel content lives
 * on their children; raster, tilemap, and reference layers carry the
 * pointers their cels need.
 */
export type LayerKind = { "kind": "raster" } | { "kind": "group", 
/**
 * Whether the group is rendered collapsed in the layer panel.
 */
collapsed: boolean, } | { "kind": "tilemap", 
/**
 * Tileset whose tiles this layer's cels reference.
 */
tileset: TilesetId, } | { "kind": "reference", 
/**
 * Pixel-buffer handle for the reference image.
 */
image: PixelBufferId, 
/**
 * Top-left placement of the image in canvas coordinates.
 */
origin: IVec2, };
