// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IVec2 } from "./IVec2";
import type { Rgba } from "./Rgba";

/**
 * One non-destructive effect in a layer's effect stack.
 *
 * Variants are intentionally CPU-cheap and deterministic so they are
 * snapshot-testable and usable as the result target for AI verbs that emit
 * overlay-style output (a generated outline, a generated tint).
 */
export type LayerEffect = { "kind": "outline", 
/**
 * Outline color.
 */
color: Rgba, 
/**
 * Outline width in pixels. Clamped to at least `1` at apply time.
 */
thickness: number, 
/**
 * Whether to include diagonal (8-connected) neighbours. `false`
 * gives the crisp 4-connected outline pixel artists usually want.
 */
diagonal: boolean, } | { "kind": "drop_shadow", 
/**
 * Shadow color (its own alpha is ignored; `opacity` drives it).
 */
color: Rgba, 
/**
 * Pixel offset of the shadow from the source.
 */
offset: IVec2, 
/**
 * Shadow strength, `0` (invisible) through `255` (full).
 */
opacity: number, } | { "kind": "brightness", 
/**
 * Per-channel delta in `-255..=255`.
 */
delta: number, } | { "kind": "invert" };
