// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Entity } from "./Entity";
import type { EntityGroup } from "./EntityGroup";
import type { Palette } from "./Palette";
import type { ProjectAi } from "./ProjectAi";
import type { TagDefinition } from "./TagDefinition";

/**
 * Top-level container of all entities, palettes, tags, and AI metadata
 * in a Pixhaus project.
 *
 * Lives on [`super::super::Project::library`] alongside the legacy
 * `sprites` field; new code targets the library, the `sprites` field is
 * the transitional path until the B9 migration completes across
 * consumers.
 */
export type Library = { 
/**
 * Stable list of entities in this project. Order matters for the
 * library tree UI (insertion order, manually re-orderable).
 */
entities?: Array<Entity>, 
/**
 * Optional groups for tree-style organization (Characters, Enemies,
 * ...). Any entity belongs to at most one group via
 * [`Entity::group_id`]. Groups can nest via
 * [`EntityGroup::parent_id`].
 */
groups?: Array<EntityGroup>, 
/**
 * Project-wide shared palettes. Entities reference by id; sprites
 * inside an entity may also have local palettes that override
 * these.
 */
palettes?: Array<Palette>, 
/**
 * Defined tags. The user creates tags here; entities reference
 * them by id. Auto-generated tags (from VLM analysis) are stored
 * here with `auto_generated = true`.
 */
tags?: Array<TagDefinition>, 
/**
 * Project-level AI metadata: style learning corpus, project `LoRA`,
 * prompt history.
 */
ai?: ProjectAi, };
