// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Direction in which a tagged or animated frame range plays.
 */
export type LoopDirection = "forward" | "reverse" | "ping_pong" | "ping_pong_reverse";
