// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifier of a per-project trained `LoRA`.
 *
 * The data model carries the id; the trained weights live next to the
 * project in a sibling file referenced by [`super::library::ProjectAi`].
 */
export type LoraId = number;
