// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetId } from "./AssetId";
import type { LoraKind } from "./LoraKind";
import type { ModelId } from "./ModelId";
import type { ReferenceImage } from "./ReferenceImage";

/**
 * Trained `LoRA` registered in the project asset library.
 */
export type LoraAsset = { id: AssetId, name: string, kind: LoraKind, trigger_word: string, target_model: ModelId, fal_lora_url: string, training_data_thumbnails?: Array<ReferenceImage>, created_at: number, };
