// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stable Pixhaus model labels. Provider-specific endpoint IDs live in
 * `pixhaus-ai`; the project file stores these product-facing identifiers.
 */
export type ModelId = "auto" | "open_ai_gpt_image2" | "google_nano_banana_pro" | "google_gemini_flash_image" | "fal_flux_kontext" | "fal_flux_dev" | "fal_recraft_vectorize" | "fal_real_esrgan";
