// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Sprite } from "./Sprite";
import type { StateId } from "./StateId";

/**
 * A named state of a `Custom`-kind entity, e.g. `idle`, `walk`,
 * `attack-1`. Wraps an existing [`Sprite`].
 */
export type NamedSprite = { 
/**
 * State id. Stable across renames so engine handoff and animation
 * references don't break.
 */
id: StateId, 
/**
 * State name. Conventional set: `idle`, `walk`, `run`, `jump`,
 * `attack`, `hurt`, `death` — but any string is valid.
 */
state_name: string, 
/**
 * The actual sprite content. The sprite's `name` field becomes the
 * display name in the editor's title bar; convention:
 * `EntityName / state_name`.
 */
sprite: Sprite, 
/**
 * Optional engine-side tags (running-state, can-be-cancelled, ...)
 * for handoff to game engines. No editor semantics.
 */
engine_tags?: Array<string>, };
