// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Required state of one neighbor cell in a custom autotile rule.
 */
export type NeighborCondition = "any" | "filled" | "empty";
