// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Rect } from "./Rect";

/**
 * Nine-slice insets for a slice's center patch.
 *
 * `center` is the inner rectangle (in pixels relative to the slice's
 * `bounds.origin`); the four edges and four corners are derived from
 * it at render time.
 */
export type NineSlice = { 
/**
 * Center patch rectangle, relative to the slice bounds.
 */
center: Rect, };
