// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SeamMatch } from "./SeamMatch";

/**
 * The measurements the normalization review surfaces.
 */
export type NormalizeReport = { 
/**
 * Worst foot-baseline deviation, in pixels, across the normalized
 * frames. `0` means every subject lands on the same baseline.
 */
baseline_drift_px: number, 
/**
 * How well subject heights agree, as a percentage. `100` means every
 * subject was already at the reference height before correction.
 */
scale_match_pct: number, 
/**
 * Loop-seam verdict between the first and last normalized frame.
 */
seam: SeamMatch, 
/**
 * The reference visible height every subject was scaled toward.
 */
reference_height: number, 
/**
 * Human-readable warnings (empty subject, large drift, scale jump).
 */
warnings?: Array<string>, };
