// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Reference-sheet operation used by model routing and project prefs.
 */
export type OperationKind = "fresh_generation" | "masked_refinement" | "prompt_only_refinement" | "regional_refinement" | "chat_turn" | "promotion" | "cross_model_grid" | "vector_export" | "upscale" | "lora_training";
