// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifier of a [`PalettePage`](super::palette::PalettePage) within a palette.
 *
 * Pages are named subset views over a palette's entries (see
 * [`PalettePage`](super::palette::PalettePage)). Each page carries its own
 * stable id so renames, reorders, and undo/redo can reference a specific
 * page without leaning on its index in the page list.
 *
 * Adapted from `OpenToonz` `toonz/sources/include/tpalette.h` under
 * BSD-3-Clause. See `THIRD_PARTY_NOTICES.md`.
 */
export type PalettePageId = number;
