// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Rgba } from "./Rgba";

/**
 * A single entry within a [`Palette`].
 *
 * The optional `name` lets artists tag colors (e.g. "skin",
 * "outline") for documentation and palette-swap workflows.
 */
export type PaletteEntry = { 
/**
 * The color value.
 */
color: Rgba, 
/**
 * Optional human-readable name for the swatch.
 */
name?: string | null, };
