// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FrameIndex } from "./FrameIndex";
import type { Rgba } from "./Rgba";

/**
 * Per-entry keyframed color changes over the project's frame range.
 *
 * Outer key: palette entry index (into [`Palette::colors`]). Inner key:
 * timeline [`FrameIndex`]. Inner value: the color the entry resolves to
 * at that frame. Frames between keys resolve to the closest preceding
 * keyframe (step semantics, no easing). Frames before the first key for
 * a given entry fall through to the caller-supplied fallback.
 *
 * Adapted from `OpenToonz` `toonz/sources/include/tpalette.h`
 * (`StyleAnimation`) under BSD-3-Clause. See `THIRD_PARTY_NOTICES.md`.
 */
export type PaletteAnimation = { 
/**
 * Per-entry keyframe table. See type-level docs for semantics.
 */
keyframes: { [key in number]: { [key in FrameIndex]: Rgba } }, };
