// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PalettePageId } from "./PalettePageId";

/**
 * A named subset view over a palette's entries.
 *
 * Pages do not own colors; they reference entries by index into the
 * parent [`Palette::colors`] vector. The same entry can appear on more
 * than one page, and pages may be reordered freely.
 *
 * Adapted from `OpenToonz` `toonz/sources/include/tpalette.h` (`class Page`)
 * under BSD-3-Clause. See `THIRD_PARTY_NOTICES.md`.
 */
export type PalettePage = { 
/**
 * Stable page identifier.
 */
id: PalettePageId, 
/**
 * Display name in the palette panel.
 */
name: string, 
/**
 * Indices into the parent palette's [`Palette::colors`] vector.
 * Out-of-range indices are tolerated by serde but should be pruned
 * by the editor on mutation.
 */
entry_indices: Array<number>, };
