// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PaletteEntry } from "./PaletteEntry";

/**
 * Replacement palette state at a specific frame.
 *
 * Aseprite stores palette changes as one full palette chunk per frame.
 * Pixhaus mirrors that by carrying a sparse list on the [`super::Sprite`]:
 * the base palette in `Sprite.palettes` covers frame 0, and each
 * override here replaces the active palette wholesale at its frame
 * boundary. Frames with no override inherit the previous frame's
 * palette state.
 */
export type PaletteFrameOverride = { 
/**
 * Frame index this override takes effect on (0-based).
 */
frame: number, 
/**
 * Replacement entries — the full palette state at this frame.
 */
colors: Array<PaletteEntry>, };
