// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PaletteEntry } from "./PaletteEntry";
import type { PaletteId } from "./PaletteId";
import type { UserData } from "./UserData";

/**
 * An ordered list of palette entries.
 *
 * Index `0` is treated as the transparent index in indexed-mode
 * sprites, mirroring Aseprite's convention. The `colors` vector may
 * be empty; downstream code should fall back to an editor default
 * palette when it is.
 */
export type Palette = { 
/**
 * Stable identifier.
 */
id: PaletteId, 
/**
 * Display name in the palette panel.
 */
name: string, 
/**
 * Ordered swatches. Position is the palette index.
 */
colors: Array<PaletteEntry>, 
/**
 * Free-form user metadata.
 */
user_data?: UserData, };
