// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Semantic role of a panel in a structure.
 */
export type PanelSlot = "view" | "expression" | "callout" | "outfit" | "palette_swatch" | "generic";
