// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Pixel bounding box for a panel within the canvas.
 */
export type PanelRect = { x: number, y: number, w: number, h: number, };
