// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TileIndex } from "./TileIndex";

/**
 * One tile's peering signature.
 */
export type PeeringTile = { 
/**
 * Expected-neighbor bitmask in `BIT_NW..BIT_SE` order. A set bit means
 * "this tile expects a matching neighbor in that direction".
 */
peering: number, 
/**
 * Tile index to place when this signature is selected.
 */
tile: TileIndex, };
