// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PeeringTile } from "./PeeringTile";
import type { TileIndex } from "./TileIndex";

/**
 * A per-tile peering bitmask set.
 */
export type PeeringSet = { 
/**
 * One entry per authored tile, in any order.
 */
tiles: Array<PeeringTile>, 
/**
 * Tile emitted when `tiles` is empty.
 */
default_tile: TileIndex, };
