// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Opaque handle to a pixel buffer held outside the data model.
 *
 * The data model does not own pixel bytes; it references them by
 * this ID. Resolution is the responsibility of whichever subsystem
 * owns the buffer registry (loader, undo stack, render compositor).
 * `u32` matches the other IDs in this module and the TS-side
 * `number` mirror; the 4-billion-buffer headroom is more than any
 * realistic editing session will mint.
 */
export type PixelBufferId = number;
