// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Opaque handle to a pixel buffer held outside the data model.
 *
 * The data model does not own pixel bytes; it references them by
 * this ID. Resolution is the responsibility of whichever subsystem
 * owns the buffer registry (loader, undo stack, render compositor).
 * Using `u64` leaves room for buffers that outlive a single
 * project session without ID reuse.
 */
export type PixelBufferId = number;
