// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActiveTarget } from "./ActiveTarget";
import type { BrushState } from "./BrushState";
import type { CanvasState } from "./CanvasState";
import type { FeatureFlags } from "./FeatureFlags";
import type { Library } from "./Library";
import type { ProjectMetadata } from "./ProjectMetadata";
import type { SchemaVersion } from "./SchemaVersion";
import type { SelectionState } from "./SelectionState";
import type { Sprite } from "./Sprite";

/**
 * The root of a Pixhaus project.
 *
 * One `Project` corresponds to one document on disk. The library
 * (B9, additive in this revision) is the canonical home for all named
 * content — entities, groups, palettes, tags, AI metadata. The
 * `sprites` and `CanvasState::active_sprite` fields remain so the
 * existing IPC commands, AI verbs, and aseprite I/O continue to
 * compile while B9.2-B9.5 migrate consumers off them; the cleanup PR
 * after B9.5 lands removes both.
 */
export type Project = { 
/**
 * Schema version. Always serialised first so a header parser can
 * decide whether to continue without decoding the rest.
 */
schema_version: SchemaVersion, 
/**
 * Optional features advertised by the writer.
 */
feature_flags: FeatureFlags, 
/**
 * Project metadata.
 */
metadata: ProjectMetadata, 
/**
 * Sprites contained in the project. May be empty during the
 * brief window between "create project" and "add first sprite".
 *
 * Transitional. New code targets [`Self::library`]; the field
 * stays in this PR so existing consumers compile, and the cleanup
 * PR after the B9 migration removes it.
 */
sprites: Array<Sprite>, 
/**
 * Project library: entities, groups, palettes, tags, AI metadata.
 *
 * Empty in fixtures written before B9 — the field carries
 * [`serde::Deserialize`]'s `default` so older `.pixhaus` archives
 * still load. New projects populate it; B9.2 onward routes IPC
 * commands through it.
 */
library?: Library, 
/**
 * Editor canvas viewport state, persisted across save/load.
 */
canvas: CanvasState, 
/**
 * Editor brush state, persisted across save/load.
 */
brush: BrushState, 
/**
 * Editor selection state, persisted across save/load.
 */
selection: SelectionState, 
/**
 * What the user is currently editing inside the library.
 *
 * Replaces [`CanvasState::active_sprite`] going forward; the old
 * field stays during the B9 migration so existing consumers
 * continue to compile.
 */
active?: ActiveTarget, };
