// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BrushState } from "./BrushState";
import type { CanvasState } from "./CanvasState";
import type { FeatureFlags } from "./FeatureFlags";
import type { ProjectMetadata } from "./ProjectMetadata";
import type { SchemaVersion } from "./SchemaVersion";
import type { SelectionState } from "./SelectionState";
import type { Sprite } from "./Sprite";

/**
 * The root of a Pixhaus project.
 *
 * One `Project` corresponds to one document on disk. A project may
 * contain multiple sprites; the editor focuses on one sprite at a
 * time via [`CanvasState::active_sprite`].
 */
export type Project = { 
/**
 * Schema version. Always serialised first so a header parser can
 * decide whether to continue without decoding the rest.
 */
schema_version: SchemaVersion, 
/**
 * Optional features advertised by the writer.
 */
feature_flags: FeatureFlags, 
/**
 * Project metadata.
 */
metadata: ProjectMetadata, 
/**
 * Sprites contained in the project. May be empty during the
 * brief window between "create project" and "add first sprite".
 */
sprites: Array<Sprite>, 
/**
 * Editor canvas viewport state, persisted across save/load.
 */
canvas: CanvasState, 
/**
 * Editor brush state, persisted across save/load.
 */
brush: BrushState, 
/**
 * Editor selection state, persisted across save/load.
 */
selection: SelectionState, };
