// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Project-level metadata: who made it, when, in what version of
 * Pixhaus.
 *
 * All strings are user-facing; keep them short. Timestamps are
 * stored as UTC seconds-since-epoch so they round-trip without
 * timezone ambiguity.
 */
export type ProjectMetadata = { 
/**
 * Display name shown in the title bar and project tree.
 */
name: string, 
/**
 * Optional human-readable description.
 */
description?: string | null, 
/**
 * Optional author string.
 */
author?: string | null, 
/**
 * UTC seconds-since-epoch at which the project was first created.
 * `i64` on the Rust side keeps the full range; the TS mirror is
 * pinned to `number` because serde_json writes plain JSON numbers
 * and seconds-since-epoch fits in `Number.MAX_SAFE_INTEGER` for
 * any realistic timestamp.
 */
created_at: number, 
/**
 * UTC seconds-since-epoch of the most recent save.
 */
updated_at: number, 
/**
 * Pixhaus build that wrote this file (e.g. `"0.1.0"`). Cosmetic
 * — version-gating happens via [`SchemaVersion`], not this field.
 */
editor_version: string, };
