// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActiveTarget } from "./ActiveTarget";
import type { BrushState } from "./BrushState";
import type { CanvasState } from "./CanvasState";
import type { FeatureFlags } from "./FeatureFlags";
import type { Library } from "./Library";
import type { ProjectMetadata } from "./ProjectMetadata";
import type { SchemaVersion } from "./SchemaVersion";
import type { SelectionState } from "./SelectionState";

/**
 * The root of a Pixhaus project.
 *
 * One `Project` corresponds to one document on disk. The
 * [`Self::library`] holds every named asset: `Custom`-kind entities
 * with their sprite states, tilesets, tilemap scenes, and references.
 * [`Self::active`] tracks what the editor is foregrounding inside the
 * library.
 *
 * Accessor methods ([`Self::sprite`], [`Self::sprite_mut`],
 * [`Self::sprites_iter`], [`Self::sprites_iter_mut`],
 * [`Self::active_sprite_id`]) walk the library so call sites don't
 * have to know about the entity / state nesting.
 */
export type Project = { 
/**
 * Schema version. Always serialised first so a header parser can
 * decide whether to continue without decoding the rest.
 */
schema_version: SchemaVersion, 
/**
 * Optional features advertised by the writer.
 */
feature_flags: FeatureFlags, 
/**
 * Project metadata.
 */
metadata: ProjectMetadata, 
/**
 * Project library: entities, groups, palettes, tags, AI metadata.
 * The canonical home for every named asset.
 */
library?: Library, 
/**
 * Editor canvas viewport state, persisted across save/load.
 */
canvas: CanvasState, 
/**
 * Editor brush state, persisted across save/load.
 */
brush: BrushState, 
/**
 * Editor selection state, persisted across save/load.
 */
selection: SelectionState, 
/**
 * What the user is currently editing inside the library.
 */
active?: ActiveTarget, };
