// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntityId } from "./EntityId";
import type { PromptHistoryEntry } from "./PromptHistoryEntry";

/**
 * Project-level AI memory.
 *
 * Per-entity AI metadata lives on [`Entity::ai`]; this struct collects
 * the project-wide pieces — the style learning corpus, the trained
 * `LoRA`, recent prompt history.
 */
export type ProjectAi = { 
/**
 * Entity ids included in the project's style reference corpus. The
 * Project Style Learning verb (S30) trains a `LoRA` from these.
 */
style_corpus?: Array<EntityId>, 
/**
 * Path to the trained `LoRA` file relative to the project directory.
 * Optional — projects without a learned style still work.
 */
project_lora_path?: string | null, 
/**
 * Recent prompts for resume-where-you-left-off semantic search.
 * Capped — the implementation details land with S21's follow-up.
 */
prompt_history?: Array<PromptHistoryEntry>, };
