// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SheetVariantId } from "./SheetVariantId";

/**
 * The outcome of a [`PromptEntry`].
 *
 * Defined minimally for B9; B10 extends this as the streaming verb
 * runtime grows new shape (intermediate previews, multiple samples,
 * failure detail).
 */
export type PromptResult = { "kind": "variant", "value": SheetVariantId } | { "kind": "error", "value": string };
