// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One entry in the per-project prompt history.
 *
 * Defined minimally for B9; the verb runtime (S21 / B10) extends the
 * shape as the streaming-prompt workflow lands.
 */
export type PromptHistoryEntry = { 
/**
 * Verb that consumed the prompt.
 */
verb_name: string, 
/**
 * The user-typed prompt text.
 */
prompt: string, 
/**
 * UTC seconds-since-epoch at which the prompt was issued.
 */
timestamp: number, };
