// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PromptResult } from "./PromptResult";

/**
 * A prompt issued against a reference sheet.
 *
 * Defined minimally for B9 — `prompt` plus optional `negative_prompt`
 * and `seed`, with the result the prompt produced. B10's sheet
 * generator extends this with backend-specific knobs (steps, CFG
 * scale, sampler) as the verb wiring lands.
 */
export type PromptEntry = { 
/**
 * The prompt text.
 */
prompt: string, 
/**
 * Optional negative prompt.
 */
negative_prompt?: string | null, 
/**
 * Optional seed for reproducible regeneration.
 */
seed?: bigint | null, 
/**
 * What the prompt produced. `None` if the prompt is queued but not
 * yet run.
 */
result?: PromptResult | null, 
/**
 * UTC seconds-since-epoch at which the prompt was issued.
 */
issued_at: number, };
