// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One fill-in-the-blank variable in a `PromptTemplate`.
 */
export type PromptVariable = { key: string, label: string, default?: string, };
