// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * High-level quality tier exposed by the reference-sheet editor.
 */
export type Quality = "auto" | "low" | "medium" | "high";
