// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IVec2 } from "./IVec2";
import type { Size } from "./Size";

/**
 * An axis-aligned rectangle in integer coordinates.
 *
 * `origin` is the top-left corner; `size` extends right and down.
 * Empty rects (zero width or height) are valid and represent
 * no-selection / no-coverage.
 */
export type Rect = { 
/**
 * Top-left corner in canvas coordinates.
 */
origin: IVec2, 
/**
 * Width and height of the rectangle.
 */
size: Size, };
