// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Opaque holder for an image referenced inside the data model.
 *
 * Pixhaus does not interpret the bytes here; it just round-trips them.
 * The `mime` hint helps the UI decide how to render — typically
 * `image/png` for B9, with B10 widening to other formats as the sheet
 * generator lands.
 */
export type ReferenceImage = { 
/**
 * Source bytes. Stored inline in B9; B10 may externalise large
 * images to a project sub-folder.
 */
bytes: Array<number>, 
/**
 * MIME type hint. `image/png` is the common case.
 */
mime: string, };
