// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Built-in reference-sheet templates exposed by core/UI.
 */
export type ReferenceSheetTemplateId = "turnaround4_view" | "turnaround8_direction" | "expression_sheet" | "action_poses" | "typographic_turnaround" | "character" | "item" | "tileset" | "custom";
