// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetId } from "./AssetId";
import type { ReferenceImage } from "./ReferenceImage";
import type { ReferenceRole } from "./ReferenceRole";

/**
 * One ordered reference image supplied to a generation/refinement request.
 */
export type ReferenceSlot = { image: ReferenceImage, role: ReferenceRole, weight: number, source_asset_id?: AssetId | null, };
