// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetId } from "./AssetId";
import type { ReferenceImage } from "./ReferenceImage";
import type { ReferenceRole } from "./ReferenceRole";
import type { SheetVariantId } from "./SheetVariantId";

/**
 * Single image saved to the project asset library.
 */
export type ReferenceAsset = { id: AssetId, image: ReferenceImage, default_role: ReferenceRole, tags?: Array<string>, source_variant_id?: SheetVariantId | null, created_at: number, };
