// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReferenceSheetTemplateId } from "./ReferenceSheetTemplateId";
import type { Rgba } from "./Rgba";
import type { SheetDimensions } from "./SheetDimensions";

/**
 * Core/UI-facing template definition. Backend-only prompt fragments stay
 * in `pixhaus-ai`.
 */
export type ReferenceSheetTemplateDefinition = { id: ReferenceSheetTemplateId, label: string, allowed_dimensions: Array<SheetDimensions>, default_dimensions: SheetDimensions, default_chroma: Rgba, benefits_from_text_labels: boolean, };
