// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetInfo } from "./AssetInfo";
import type { PromptEntry } from "./PromptEntry";
import type { SheetVariant } from "./SheetVariant";

export type ReferenceSheet = {
canonical: SheetVariant | null,
variants?: Array<SheetVariant>,
prompts?: Array<PromptEntry>,
info?: AssetInfo,
};
