// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Role hint for one reference image slot.
 */
export type ReferenceRole = "subject" | "style" | "pose" | "outfit" | "context" | "generic";
