// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReferenceImage } from "./ReferenceImage";
import type { RegionDefinition } from "./RegionDefinition";

/**
 * Refinement metadata stored on variants produced by refinement.
 */
export type RefinementKind = { "kind": "masked", "value": { mask_png: ReferenceImage, } } | { "kind": "prompt_only" } | { "kind": "regional", "value": { regions: Array<RegionDefinition>, } };
