// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IVec2 } from "./IVec2";
import type { ReferenceSlot } from "./ReferenceSlot";

/**
 * Region used by regional reference refinement.
 */
export type RegionDefinition = { polygon?: Array<IVec2>, prompt: string, region_references?: Array<ReferenceSlot>, };
