// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One resolved variable for a saved Prompt: the declared (or detected) key,
 * its label and default, and any best-effort autofilled value.
 */
export type ResolvedVariable = { 
/**
 * The variable key as it appears in `{token}` form.
 */
key: string, 
/**
 * Display label. Defaults to `key` for auto-detected tokens.
 */
label: string, 
/**
 * Default value. Empty for auto-detected tokens.
 */
default: string, 
/**
 * Best-effort value pulled from the target entity's metadata, if any.
 */
autofilled: string | null, };
