// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single 8-bit-per-channel RGBA color.
 *
 * Channels are non-premultiplied; conversion to premultiplied space
 * happens in the rendering layer, not in the data model.
 */
export type Rgba = { 
/**
 * Red channel.
 */
r: number, 
/**
 * Green channel.
 */
g: number, 
/**
 * Blue channel.
 */
b: number, 
/**
 * Alpha channel. `0` is fully transparent, `255` fully opaque.
 */
a: number, };
