// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Selectable arbitrary-angle rotation algorithm for the transform tool.
 *
 * Pixel-art rotation has no single best algorithm, so the tool exposes a
 * choice. The three CPU algorithms here cover the practical range: crisp
 * ([`RotationAlgorithm::NearestNeighbor`]), smooth
 * ([`RotationAlgorithm::Bilinear`]), and diagonal-preserving
 * ([`RotationAlgorithm::RotSprite`]). The remaining `RotSprite`-family
 * variants (`CleanEdge`, `OmniScale`, `RotxelSmear`) are GPU shaders that
 * belong to the WebGL2 viewport (Tier S in the adoption catalog) and are
 * tracked there.
 */
export type RotationAlgorithm = "nearest_neighbor" | "bilinear" | "rot_sprite";
