// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Versioned identity of the data model.
 *
 * Encoded explicitly so old binaries can refuse to load files written
 * by a newer major version, and so newer binaries can transparently
 * upgrade older minor versions.
 */
export type SchemaVersion = { 
/**
 * Breaking-change counter. A reader must reject files whose
 * `major` is higher than the one it was built against.
 */
major: number, 
/**
 * Additive-change counter. A reader may load files with a higher
 * `minor` than its own, ignoring fields it doesn't recognise.
 */
minor: number, };
