// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Loop-seam verdict: how close the last frame is to the first.
 */
export type SeamMatch = "ok" | "close" | "drift";
