// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PixelBufferId } from "./PixelBufferId";
import type { Rect } from "./Rect";

/**
 * The shape of a selection.
 *
 * A `Rect` selection is rectangular and exact. A `Mask` selection is
 * arbitrary-shape, with the actual mask bytes held in a pixel buffer
 * referenced by [`PixelBufferId`].
 */
export type SelectionRegion = { "kind": "rect", 
/**
 * Selection bounds in canvas coordinates.
 */
bounds: Rect, } | { "kind": "mask", 
/**
 * Bounding rectangle of the mask in canvas coordinates.
 */
bounds: Rect, 
/**
 * Handle to the mask pixel buffer.
 */
mask: PixelBufferId, };
