// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LayerId } from "./LayerId";
import type { SelectionRegion } from "./SelectionRegion";

/**
 * The current selection on the canvas.
 */
export type SelectionState = { 
/**
 * What kind of region is selected. `None` means nothing is
 * selected; the canvas treats every pixel as eligible.
 */
region?: SelectionRegion | null, 
/**
 * Layer the selection is anchored to. Some operations (e.g.
 * "fill selection") require a target layer.
 */
anchor_layer?: LayerId | null, };
