// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Rect } from "./Rect";

/**
 * One labelled panel within a sheet.
 */
export type SheetPanel = { 
/**
 * Rectangle within the sheet image.
 */
region: Rect, 
/**
 * Semantic label: `front`, `side-left`, `happy`, `scar-over-eye`.
 */
label: string, };
