// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifier of a [`SheetVariant`](super::library::SheetVariant) within
 * a [`ReferenceSheet`](super::library::ReferenceSheet).
 *
 * Reference sheets keep older variants in their `history`; the id makes
 * it possible to point at one specific variant from a generation log.
 */
export type SheetVariantId = number;
