// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GenerationProvenance } from "./GenerationProvenance";
import type { PaletteEntry } from "./PaletteEntry";
import type { ReferenceImage } from "./ReferenceImage";
import type { SheetComposition } from "./SheetComposition";
import type { SheetVariantId } from "./SheetVariantId";

/**
 * One generated version of a reference sheet.
 *
 * The sheet is one composite image with optional panel rectangles
 * describing the turnaround views, expressions, callouts, and outfit
 * variants inside it. B9 ships the type; B10 populates `composition`
 * with real panel data.
 */
export type SheetVariant = { 
/**
 * Stable identifier within the parent [`ReferenceSheet`].
 */
id: SheetVariantId, 
/**
 * UTC seconds-since-epoch at which this variant was generated or
 * imported.
 */
generated_at: number, 
/**
 * The composite sheet image.
 */
image: ReferenceImage, 
/**
 * What's in the sheet, panel by panel. Empty in B9; B10 fills it.
 */
composition?: SheetComposition, 
/**
 * Generation provenance. `None` in B9 for user-uploaded references;
 * B10's generator populates these.
 */
generation?: GenerationProvenance | null, 
/**
 * Palette extracted from the sheet image. Empty in B9; B10's
 * generator runs eyedropper extraction at sheet-creation time.
 */
extracted_palette?: Array<PaletteEntry>, };
