// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Width/height pair for template-controlled sheet output sizes.
 */
export type SheetDimensions = { width: number, height: number, };
