// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetId } from "./AssetId";
import type { ChatTranscript } from "./ChatTranscript";
import type { GenerationProvenance } from "./GenerationProvenance";
import type { ModelId } from "./ModelId";
import type { PaletteEntry } from "./PaletteEntry";
import type { Quality } from "./Quality";
import type { ReferenceImage } from "./ReferenceImage";
import type { ReferenceSheetTemplateId } from "./ReferenceSheetTemplateId";
import type { ReferenceSlot } from "./ReferenceSlot";
import type { RefinementKind } from "./RefinementKind";
import type { Rgba } from "./Rgba";
import type { SheetComposition } from "./SheetComposition";
import type { SheetVariantId } from "./SheetVariantId";
import type { VariantOrigin } from "./VariantOrigin";

/**
 * One generated/imported/refined version of a reference sheet.
 *
 * The raster image is always embedded. Optional vector output is stored
 * as another [`ReferenceImage`] with `mime = "image/svg+xml"`.
 */
export type SheetVariant = {
/**
 * Stable identifier within the parent [`ReferenceSheet`].
 */
id: SheetVariantId,
/**
 * UTC seconds-since-epoch at which this variant was generated or
 * imported.
 */
created_at: number,
/**
 * Layout template used to generate this sheet.
 */
template: ReferenceSheetTemplateId,
/**
 * Output raster width.
 */
width: number,
/**
 * Output raster height.
 */
height: number,
/**
 * Flat chroma-key background color requested for the model.
 */
chroma_color: Rgba,
/**
 * User-typed prompt for this operation.
 */
user_prompt?: string,
/**
 * Full composed prompt after style notes/template/reference hints.
 */
composed_prompt?: string,
/**
 * Ordered generation references with role hints.
 */
references?: Array<ReferenceSlot>,
/**
 * Whether Google Search grounding was requested.
 */
real_world_grounding: boolean,
/**
 * Applied LoRA asset, Flux-only.
 */
applied_lora?: AssetId | null,
/**
 * Applied LoRA strength for Flux requests.
 */
lora_weight?: number,
/**
 * The composite sheet image.
 */
image: ReferenceImage,
/**
 * Optional vectorized SVG output.
 */
vector_image?: ReferenceImage | null,
/**
 * Model that produced this variant.
 */
model: ModelId,
/**
 * Quality tier used for the run.
 */
quality: Quality,
/**
 * Parent/source variant for refinements, chat turns, promotions, and
 * cross-model comparisons.
 */
parent_variant_id?: SheetVariantId | null,
/**
 * Operation origin.
 */
origin: VariantOrigin,
/**
 * Refinement-specific metadata.
 */
refinement?: RefinementKind | null,
/**
 * Full chat transcript for chat-generated variants.
 */
chat_transcript?: ChatTranscript | null,
/**
 * True when produced by "Promote to final".
 */
promotion: boolean,
/**
 * Actual cost recorded after completion, if known.
 */
cost_usd?: number | null,
/**
 * What's in the sheet, panel by panel. Empty in B9; B10 fills it.
 */
composition?: SheetComposition,
/**
 * Generation provenance. `None` in B9 for user-uploaded references;
 * B10's generator populates these.
 */
generation?: GenerationProvenance | null,
/**
 * Palette extracted from the sheet image. Empty in B9; B10's
 * generator runs eyedropper extraction at sheet-creation time.
 */
extracted_palette?: Array<PaletteEntry>, };
