// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Rect } from "./Rect";
import type { SheetPanel } from "./SheetPanel";

/**
 * Panel rectangles within a sheet image, labelled by what they show.
 */
export type SheetComposition = { 
/**
 * Full-body view rectangles: front, side, three-quarter, back.
 */
views?: Array<SheetPanel>, 
/**
 * Facial expression panels: happy, angry, surprised, ...
 */
expressions?: Array<SheetPanel>, 
/**
 * Detail close-ups: scars, accessories, tattoos, runes.
 */
callouts?: Array<SheetPanel>, 
/**
 * Outfit / equipment variations.
 */
outfits?: Array<SheetPanel>, 
/**
 * Palette swatch rectangle, if the sheet includes one.
 */
palette_swatch?: Rect | null, };
