// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A non-empty 2D extent in pixels.
 *
 * Represented as `u32` so canvas dimensions are unambiguously
 * non-negative. A zero-width or zero-height canvas is rejected at the
 * editor layer; the type itself permits zero only because `Default`
 * must be defined.
 */
export type Size = { 
/**
 * Width in pixels.
 */
width: number, 
/**
 * Height in pixels.
 */
height: number, };
