// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SliceId } from "./SliceId";
import type { SliceKey } from "./SliceKey";
import type { UserData } from "./UserData";

/**
 * A named rectangular region on the sprite.
 *
 * `keys` is non-empty when constructed by the editor; the first key
 * holds the slice's base geometry and subsequent keys are per-frame
 * overrides.
 */
export type Slice = { 
/**
 * Stable identifier.
 */
id: SliceId, 
/**
 * Display name. Exporters use this verbatim as the engine-side
 * sub-asset name.
 */
name: string, 
/**
 * Per-frame slice geometry. Index `0` is the base; later entries
 * override starting at their declared `frame`.
 */
keys: Array<SliceKey>, 
/**
 * Free-form user metadata.
 */
user_data?: UserData, };
