// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FrameIndex } from "./FrameIndex";
import type { NineSlice } from "./NineSlice";
import type { Pivot } from "./Pivot";
import type { Rect } from "./Rect";

/**
 * A per-frame override of a slice's geometry.
 */
export type SliceKey = { 
/**
 * Frame from which this key takes effect (until the next key).
 */
frame: FrameIndex, 
/**
 * The slice rectangle in canvas coordinates.
 */
bounds: Rect, 
/**
 * Optional nine-slice insets.
 */
nine_slice?: NineSlice | null, 
/**
 * Optional pivot point (relative to `bounds.origin`).
 */
pivot?: Pivot | null, };
