// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifier of a [`Sprite`](super::sprite::Sprite) within a project.
 */
export type SpriteId = number;
