// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Animation } from "./Animation";
import type { Cel } from "./Cel";
import type { ColorMode } from "./ColorMode";
import type { Frame } from "./Frame";
import type { FrameTag } from "./FrameTag";
import type { Layer } from "./Layer";
import type { Palette } from "./Palette";
import type { Size } from "./Size";
import type { Slice } from "./Slice";
import type { SpriteId } from "./SpriteId";
import type { Tileset } from "./Tileset";
import type { UserData } from "./UserData";

/**
 * A sprite within a Pixhaus project.
 */
export type Sprite = { 
/**
 * Stable identifier within the parent project.
 */
id: SpriteId, 
/**
 * Display name in the project tree.
 */
name: string, 
/**
 * Canvas dimensions in pixels.
 */
canvas: Size, 
/**
 * Authoring color mode.
 */
color_mode: ColorMode, 
/**
 * Layer stack. Order matters: index `0` is the bottom layer.
 */
layers: Array<Layer>, 
/**
 * Frame timeline. Index is the frame number; `frames.len()` is
 * the total animation length.
 */
frames: Array<Frame>, 
/**
 * Cels: per-(layer, frame) drawn content. Sparse — a layer with
 * no content on a frame simply has no entry.
 */
cels: Array<Cel>, 
/**
 * Palettes available within this sprite.
 */
palettes: Array<Palette>, 
/**
 * Tilesets available within this sprite.
 */
tilesets: Array<Tileset>, 
/**
 * Editor-side frame tags (named ranges).
 */
frame_tags: Array<FrameTag>, 
/**
 * Engine-side animation entries (frame ranges + handoff metadata).
 */
animations: Array<Animation>, 
/**
 * Named rectangular regions used for nine-slice and pivots.
 */
slices: Array<Slice>, 
/**
 * Free-form user metadata.
 */
user_data?: UserData, };
