// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifier of a state within a Custom-kind entity.
 *
 * A `Custom("Character")` entity holds named states such as `idle`,
 * `walk`, `attack`. The id stays stable across state renames so engine
 * handoff metadata and animation references don't break.
 */
export type StateId = number;
