// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Vertex } from "./Vertex";

/**
 * A single styled stroke: a polyline of `Vertex` values plus the
 * palette style ID that drives its rendering.
 */
export type Stroke = { 
/**
 * Ordered vertices that define the centerline.
 */
vertices: Array<Vertex>, 
/**
 * Palette style ID. Currently always `0` — wiring up the style
 * classifier is a follow-up stream.
 */
style_id: number, };
