// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PanelRect } from "./PanelRect";
import type { PanelSlot } from "./PanelSlot";

/**
 * One named panel within a paneled structure.
 */
export type StructurePanel = { label: string, rect: PanelRect, 
/**
 * Prose with `{canvas_w}`, `{canvas_h}`, `{panel_w}`, `{panel_h}`,
 * `{label}` tokens interpolated by the resolver.
 */
prose_fragment: string, slot: PanelSlot, };
