// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stable id for a Structure. Built-ins use reverse-DNS
 * (`pixhaus.builtin.structure.character`); a project record reuses that id
 * to shadow the built-in, or takes a fresh project slug.
 */
export type StructureId = string;
