// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Rgba } from "./Rgba";
import type { TagId } from "./TagId";

/**
 * Definition of a tag the user (or VLM auto-tagging) created.
 */
export type TagDefinition = { 
/**
 * Stable identifier.
 */
id: TagId, 
/**
 * Tag name. User-facing; must be non-empty in the editor but the
 * data model itself does not enforce that.
 */
name: string, 
/**
 * Optional accent color, used by the library tree to tint the chip.
 */
color?: Rgba | null, 
/**
 * `true` if created by VLM auto-tagging. Lets the UI display them
 * differently and lets the user accept/reject them in batch.
 */
auto_generated: boolean, };
