// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TileCell } from "./TileCell";

/**
 * A grid of [`TileCell`]s in row-major order.
 *
 * Cells are addressed by `cells[y * width + x]`. Helpers on this type
 * stay non-panicking and bounds-checked; SIMD/iteration helpers land
 * alongside the renderer in stream S06.
 */
export type TilemapData = { 
/**
 * Number of columns.
 */
width: number, 
/**
 * Number of rows.
 */
height: number, 
/**
 * Cells in row-major order. Length must equal `width * height`.
 */
cells: Array<TileCell>, };
