// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntityId } from "./EntityId";
import type { TileIndex } from "./TileIndex";

/**
 * One reference from a [`TilemapScene`] to a `Tileset` entity.
 */
export type TilesetReference = { 
/**
 * Stable id of the `Tileset` entity in the project library.
 */
tileset_entity_id: EntityId, 
/**
 * First global tile id for this tileset (TMX-compat). The exporter
 * uses this to translate per-cell `TileIndex` values into Tiled
 * global ids.
 */
first_gid: TileIndex, };
