// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AutotileKind } from "./AutotileKind";
import type { HexOffsetAxis } from "./HexOffsetAxis";
import type { Size } from "./Size";
import type { TileProperties } from "./TileProperties";
import type { TileShape } from "./TileShape";
import type { TilesetId } from "./TilesetId";
import type { TilesetSource } from "./TilesetSource";
import type { UserData } from "./UserData";

/**
 * A tileset.
 */
export type Tileset = { 
/**
 * Stable identifier.
 */
id: TilesetId, 
/**
 * Display name in the tileset panel.
 */
name: string, 
/**
 * Width and height of one tile in pixels.
 */
tile_size: Size, 
/**
 * Grid geometry tilemaps using this tileset are laid out with.
 * Defaults to [`TileShape::Square`]; files written before tile shapes
 * existed load as square and re-save with the field omitted.
 */
shape?: TileShape, 
/**
 * Which rows/columns take the half-step offset for hex shapes. `None`
 * for square and isometric grids.
 */
hex_offset?: HexOffsetAxis | null, 
/**
 * Number of tiles the tileset declares. Index `0` is the empty
 * tile by convention; `tile_count` includes that index.
 */
tile_count: number, 
/**
 * Index displayed for the first non-empty tile. Aseprite stores
 * this so a tileset can present itself as 1-based ("tile 1") or
 * 0-based ("tile 0") in its UI without renumbering pixel data.
 * Tile id `0` always remains the empty tile internally.
 */
base_index: number, 
/**
 * Where the tile pixels live.
 */
source: TilesetSource, 
/**
 * Per-tile metadata. Length may be less than `tile_count`; indices
 * beyond the vec length implicitly have `TileProperties::default()`.
 */
properties?: Array<TileProperties>, 
/**
 * Autotile rule set bound to this tileset, if any. Standard kinds
 * (`Blob47`, `Corner16`, `Minimal4`) need no extra data; the
 * `Custom` variant carries its own rules + default tile.
 */
autotile?: AutotileKind | null, 
/**
 * Free-form user metadata.
 */
user_data?: UserData, };
