// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Index of a tile within a tileset.
 *
 * Index `0` is conventionally the empty / transparent tile. Code
 * that walks a tilemap should treat `TileIndex(0)` as "no tile"
 * rather than reading from the tileset.
 */
export type TileIndex = number;
