// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LayerId } from "./LayerId";
import type { TilemapData } from "./TilemapData";

/**
 * One layer within a [`TilemapScene`].
 */
export type TilemapLayer = { 
/**
 * Stable id within the scene.
 */
id: LayerId, 
/**
 * Display name (e.g. `ground`, `decorations`, `collision`).
 */
name: string, 
/**
 * Cell data.
 */
data: TilemapData, 
/**
 * Per-layer alpha multiplier (`0..=255`).
 */
opacity: number, 
/**
 * Layer visibility toggle.
 */
visible: boolean, };
