// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Grid geometry of a tilemap that draws from this tileset.
 *
 * One tileset handles square, isometric, and both hex orientations via this
 * parameter; cell-to-pixel math (see `core::tilemap::cell_to_pixel`) switches
 * on it while the rest of the tilemap stack stays shape-agnostic.
 *
 * Adopted from Pixelorama's `TileSetCustom` `tile_shape`
 * (`src/Classes/Cels/CelTileMap.gd`). See `THIRD_PARTY_NOTICES.md`.
 */
export type TileShape = "square" | "isometric" | "hex_pointy" | "hex_flat";
