// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Size } from "./Size";
import type { TilesetId } from "./TilesetId";
import type { TilesetSource } from "./TilesetSource";
import type { UserData } from "./UserData";

/**
 * A tileset.
 */
export type Tileset = { 
/**
 * Stable identifier.
 */
id: TilesetId, 
/**
 * Display name in the tileset panel.
 */
name: string, 
/**
 * Width and height of one tile in pixels.
 */
tile_size: Size, 
/**
 * Number of tiles the tileset declares. Index `0` is the empty
 * tile by convention; `tile_count` includes that index.
 */
tile_count: number, 
/**
 * Where the tile pixels live.
 */
source: TilesetSource, 
/**
 * Free-form user metadata.
 */
user_data?: UserData, };
