// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-cell rendering flags for a tile placement.
 *
 * Stored as a `u8` bitfield so a tilemap of `W*H` cells is small
 * regardless of grid size. Flag combinations let a single tile in
 * the source set cover four orientations and the diagonal flip.
 */
export type TileFlags = number;
