// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PixelBufferId } from "./PixelBufferId";

/**
 * Where a tileset's pixel data is stored.
 */
export type TilesetSource = { "kind": "inline", 
/**
 * Handle to the packed tile buffer.
 */
buffer: PixelBufferId, } | { "kind": "external", 
/**
 * Project-root-relative path to the tileset image.
 */
path: string, };
