// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TileIndex } from "./TileIndex";
import type { Tileset } from "./Tileset";

/**
 * Result of [`tileset_add_tile`]: the updated tileset and the index of
 * the newly captured tile.
 */
export type TilesetAddTileResult = { 
/**
 * Tileset with `tile_count` incremented and (potentially) a
 * freshly-allocated atlas buffer.
 */
tileset: Tileset, 
/**
 * Index of the new tile (i.e. previous `tile_count`). Suitable for
 * `selectedTileIndex` so the user can immediately paint with it.
 */
index: TileIndex, };
