// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TileIndex } from "./TileIndex";

/**
 * One frame in a tile animation sequence.
 */
export type TileAnimationFrame = { 
/**
 * Source tile index inside the same tileset.
 */
tile_index: TileIndex, 
/**
 * Display duration of this frame in milliseconds.
 */
duration_ms: number, };
