// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnimLoopMode } from "./AnimLoopMode";
import type { TileAnimationFrame } from "./TileAnimationFrame";

/**
 * Animation sequence attached to a tile.
 *
 * Animated tiles are the canonical representation: tile `n` in the
 * tileset carries this struct; the renderer advances through `frames`
 * according to `loop_mode` at playback time (see `core::tilemap::animate`).
 */
export type TileAnimation = { 
/**
 * Ordered list of frames (must be non-empty after validation).
 */
frames: Array<TileAnimationFrame>, 
/**
 * What happens when the last frame finishes.
 */
loop_mode: AnimLoopMode, };
