// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TileFlags } from "./TileFlags";
import type { TileIndex } from "./TileIndex";

/**
 * One cell of a tilemap.
 */
export type TileCell = { 
/**
 * Index of the tile in the layer's tileset. `TileIndex(0)` is
 * the empty tile by convention.
 */
index: TileIndex, 
/**
 * Rendering flags for this cell.
 */
flags: TileFlags, };
