// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Size } from "./Size";
import type { TilemapLayer } from "./TilemapLayer";
import type { TilesetReference } from "./TilesetReference";

/**
 * A level scene that references one or more `Tileset` entities and
 * places tiles on layered grids.
 */
export type TilemapScene = { 
/**
 * Grid dimensions in tile cells.
 */
size: Size, 
/**
 * References to `Tileset` entities used by this scene. Each
 * reference gets a `first_gid` for Tiled-compat export (TMX uses
 * global tile ids that disambiguate across multiple tilesets).
 */
tilesets?: Array<TilesetReference>, 
/**
 * Tile cell layers.
 */
layers?: Array<TilemapLayer>, 
/**
 * Free-form key/value properties for engine handoff (e.g. `music =
 * forest-theme.ogg`).
 */
properties?: { [key in string]: string }, };
