// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CollisionShape } from "./CollisionShape";
import type { TileAnimation } from "./TileAnimation";

/**
 * Per-tile metadata stored alongside the tileset.
 *
 * Indexed by [`TileIndex`] — the entry at position `i` describes tile `i`.
 * The `Tileset` stores a sparse `Vec<TileProperties>` that is resized to
 * match `tile_count`; out-of-bounds indices default to
 * `TileProperties::default()` (no collision, no animation).
 */
export type TileProperties = { 
/**
 * Collision shape for this tile.
 */
collision?: CollisionShape, 
/**
 * Animation sequence, if any.
 */
animation?: TileAnimation | null, };
