// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifier of an async `LoRA` training job tracked by
 * [`TrainingJob`](super::library::TrainingJob).
 */
export type TrainingJobId = number;
