// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetId } from "./AssetId";
import type { LoraKind } from "./LoraKind";
import type { ModelId } from "./ModelId";
import type { TrainingJobId } from "./TrainingJobId";
import type { TrainingStatus } from "./TrainingStatus";

/**
 * Async `LoRA` training job record.
 */
export type TrainingJob = { id: TrainingJobId, asset_name: string, kind: LoraKind, target_model: ModelId, trigger_word: string, training_data?: Array<AssetId>, fal_job_id: string, status: TrainingStatus, created_at: number, completed_at?: number | null, result_lora_id?: AssetId | null, error?: string | null, };
