// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * State of a fal LoRA training job.
 */
export type TrainingStatus = "queued" | "running" | "completed" | "failed" | "cancelled";
