// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UpdateInfo } from "./UpdateInfo";

/**
 * Payload emitted on the `updater:available` event.
 */
export type UpdateAvailablePayload = { 
/**
 * Available update details.
 */
update: UpdateInfo, };
