// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Payload emitted on the `updater:progress` event during download.
 */
export type UpdateProgressPayload = { 
/**
 * Bytes downloaded so far.
 */
downloaded: bigint, 
/**
 * Total bytes to download, if the server reported `Content-Length`.
 */
total: bigint | null, };
