// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Metadata returned to the frontend when an update is available.
 */
export type UpdateInfo = { 
/**
 * `SemVer` version string of the available release, e.g. `"0.2.0"`.
 */
version: string, 
/**
 * Release notes extracted from the update manifest (Markdown).
 */
body: string | null, 
/**
 * RFC 3339 publication timestamp of the release.
 */
date: string | null, };
