// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Rgba } from "./Rgba";

/**
 * Optional user-supplied text and tint color attached to an entity.
 *
 * Both fields are optional so a missing `UserData` and a present-but-
 * empty `UserData` round-trip identically.
 */
export type UserData = { 
/**
 * Short user-supplied label or note.
 */
text?: string | null, 
/**
 * Optional accent color, used by the editor to tint a row.
 */
color?: Rgba | null, };
