// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Source operation that produced a sheet variant.
 */
export type VariantOrigin = "fresh_generation" | "refinement" | "chat_turn" | "promotion" | "cross_model_grid" | "manual_import";
