// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Stroke } from "./Stroke";

/**
 * The result of vectorizing a raster ink layer.
 */
export type VectorImage = { 
/**
 * All strokes extracted from the input raster.
 */
strokes: Array<Stroke>, 
/**
 * Width of the source raster, in pixels.
 */
width: number, 
/**
 * Height of the source raster, in pixels.
 */
height: number, };
