// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single vertex on a stroke's centerline.
 *
 * Coordinates are in raster pixel space (top-left origin). `thickness`
 * is the local stroke half-width — the distance from the centerline
 * to either edge at this vertex.
 */
export type Vertex = { 
/**
 * Horizontal coordinate in pixel space.
 */
x: number, 
/**
 * Vertical coordinate in pixel space.
 */
y: number, 
/**
 * Local stroke half-width at this vertex.
 */
thickness: number, };
