[package]
name = "pixhaus-ui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
egui.workspace = true
egui-wgpu.workspace = true
wgpu.workspace = true
pixhaus-render = { path = "../render" }

[lints]
workspace = true
