[package]
name = "pixhaus-ui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
egui.workspace = true
egui-wgpu.workspace = true
egui-phosphor.workspace = true
wgpu.workspace = true
serde.workspace = true
thiserror.workspace = true
tracing.workspace = true
pixhaus-render = { path = "../render" }

[dev-dependencies]
rstest.workspace = true
insta.workspace = true

[lints]
workspace = true
