[package]
name = "pixhaus-io"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Pixhaus file I/O: .pixhaus, .aseprite, .psd, png, .tmx"

[dependencies]
pixhaus-core = { path = "../core" }
serde.workspace = true
thiserror.workspace = true
rmp-serde.workspace = true
zstd.workspace = true

[dev-dependencies]
anyhow.workspace = true
rmp-serde.workspace = true
rstest.workspace = true

[lints]
workspace = true
