[package]
name = "pixhaus-io"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Pixhaus file I/O: .pixhaus, .aseprite, .psd, png, .tmx"

[dependencies]
pixhaus-core = { path = "../core" }
flate2.workspace = true
image.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
rmp-serde.workspace = true
zstd.workspace = true

[dev-dependencies]
anyhow.workspace = true
criterion.workspace = true
rstest.workspace = true

[[bench]]
name = "pixhaus_perf"
harness = false

[lints]
workspace = true
