//! Generates `src/selection/skeleton_lut.rs` from the 8-neighbour
//! classification rules. Run by cargo before compiling the crate.
//!
//! Adapted from `OpenToonz` `toonz/sources/common/trop/tautoclose.cpp`
//! and `toonz/sources/toonzlib/skeletonlut.h` under BSD-3-Clause.
//! See `THIRD_PARTY_NOTICES.md`.
//!
//! The `OpenToonz` `SkeletonLut` is a hand-typed 256-entry table. We
//! derive the table from the underlying enumeration rules instead so
//! the result is reviewable: every code maps to a single classification
//! by counting set bits and walking the 8-neighbour ring.

use std::env;
use std::fs;
use std::io::{self, Write};
use std::path::Path;

#[derive(Copy, Clone, Debug, Eq, PartialEq)]
enum Classification {
    Isolated,
    Endpoint,
    Border,
    Branch,
    Interior,
}

fn classify(code: u8) -> Classification {
    let n = code.count_ones();
    match n {
        0 => Classification::Isolated,
        1 => Classification::Endpoint,
        2 => {
            // Two set bits: border if the bits are adjacent in the
            // 8-neighbour ring (i and i+1 mod 8); endpoint otherwise.
            if adjacent_pair(code) {
                Classification::Border
            } else {
                Classification::Endpoint
            }
        }
        3 | 4 => {
            // For 3 or 4 set bits the pattern is a branch iff it
            // contains three or more disjoint runs around the ring.
            // Two adjacent runs read as a thick border; three runs
            // can only be a junction.
            if disjoint_runs(code) >= 3 {
                Classification::Branch
            } else {
                Classification::Border
            }
        }
        _ => Classification::Interior,
    }
}

fn adjacent_pair(code: u8) -> bool {
    for i in 0..8u32 {
        let a = (code >> i) & 1;
        let b = (code >> ((i + 1) % 8)) & 1;
        if a == 1 && b == 1 {
            return true;
        }
    }
    false
}

fn disjoint_runs(code: u8) -> u32 {
    // Number of distinct contiguous arcs of set bits around the 8-ring.
    // Equal to the number of 1->0 transitions traversing the ring once.
    let mut runs = 0;
    for i in 0..8u32 {
        let cur = (code >> i) & 1;
        let nxt = (code >> ((i + 1) % 8)) & 1;
        if cur == 1 && nxt == 0 {
            runs += 1;
        }
    }
    runs
}

fn main() -> io::Result<()> {
    let out_dir = env::var_os("OUT_DIR")
        .ok_or_else(|| io::Error::new(io::ErrorKind::NotFound, "OUT_DIR not set by cargo"))?;
    let dest = Path::new(&out_dir).join("skeleton_lut_table.rs");
    let mut f = fs::File::create(&dest)?;

    writeln!(f, "// AUTOGENERATED by core/build.rs — DO NOT EDIT.")?;
    writeln!(
        f,
        "pub(crate) static SKELETON_LUT: [Classification; 256] = ["
    )?;
    for code in 0u32..256 {
        // 0..256 fits in u8 by construction; use try_from to keep the
        // truncation lint happy and surface any rules-edit mistake.
        let byte = u8::try_from(code)
            .map_err(|e| io::Error::other(format!("code {code} out of range: {e}")))?;
        let c = classify(byte);
        writeln!(f, "    Classification::{c:?},")?;
    }
    writeln!(f, "];")?;

    println!("cargo:rerun-if-changed=build.rs");
    Ok(())
}
