[package]
name = "pixhaus-mod-sprite-edit"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
egui.workspace = true
egui-phosphor.workspace = true
pixhaus-ui = { path = "../../crates/ui" }

[lints]
workspace = true
