//! Headless acceptance test for the foundation spine (bible 25.2 minus the UI).
//!
//! Submit a generation job to the mock provider, wait for it to complete, take the
//! result, apply it as a sprite through the history, confirm it composites to the
//! generated bytes, and undo it away. This is the whole prompt -> job -> result ->
//! command -> undo loop with no window.

#![allow(clippy::disallowed_methods, clippy::unwrap_used, clippy::expect_used)]

use std::sync::Arc;
use std::sync::mpsc::{Receiver, TryRecvError};
use std::time::Duration;

use pixhaus_core::{ApplyGeneratedAsset, Document, composite_sprite};
use pixhaus_mod_providers::MockProvider;
use pixhaus_services::job::{GenerationContext, GenerationJobInput, GenerationKind, JobManager, JobMsg};
use pixhaus_services::provider::{ProviderCapability, ProviderRegistry};
use pixhaus_services::{History, ResultStore};

async fn wait_for_completed(rx: &Receiver<JobMsg>) {
    for _ in 0..5000 {
        match rx.try_recv() {
            Ok(JobMsg::Completed { .. }) | Err(TryRecvError::Disconnected) => return,
            Ok(_) => {}
            Err(TryRecvError::Empty) => tokio::time::sleep(Duration::from_millis(1)).await,
        }
    }
}

#[tokio::test]
async fn prompt_to_mock_result_to_command_to_undo() {
    // Build the spine.
    let mut doc = Document::new();
    let mut history = History::new();
    let mut providers = ProviderRegistry::new();
    providers.register(Arc::new(MockProvider::with_delay(Duration::from_millis(2))));
    let results = Arc::new(ResultStore::new());
    let (tx, rx) = std::sync::mpsc::channel();
    let mut jobs = JobManager::new(tx);

    // Submit via capability lookup, never by naming the mock directly.
    let provider = providers.first_with(ProviderCapability::TextToSprite).expect("mock provides text-to-sprite");
    let input = GenerationJobInput {
        prompt: "a small knight".to_owned(),
        seed: 99,
        size: (16, 16),
        context: GenerationContext::NewAsset,
        kind: GenerationKind::Anchor,
    };
    jobs.submit(provider, input, results.clone());

    // Drain until the result lands in the store.
    wait_for_completed(&rx).await;
    assert_eq!(results.len(), 1);

    // Apply the selected result as a new sprite, through the history.
    let asset = results.selected().expect("a result is selected");
    let cmd = ApplyGeneratedAsset::new("knight".to_owned(), asset.width, asset.height, asset.stride, asset.rgba.clone());
    history.execute(&mut doc, Box::new(cmd)).unwrap();

    // The sprite is on the canvas and composites to the generated bytes.
    let id = doc.active_sprite().expect("a sprite is active");
    assert_eq!(composite_sprite(&doc, id).unwrap().as_bytes(), asset.rgba.as_slice());

    // Undo removes it.
    history.undo(&mut doc).unwrap();
    assert_eq!(doc.sprites().len(), 0);
}
